source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'QuramiLink_Example', :exclusive => true do
  pod "QuramiLink", :path => "../"
end

target 'QuramiLink_Tests', :exclusive => true do
  pod "QuramiLink", :path => "../"

  
end
